vdus:
  VDU1:
    config:
      firewall: |
        package firewall
        config defaults
            option syn_flood '1'
            option input 'ACCEPT'
            option output 'ACCEPT'
            option forward 'REJECT'
        config zone
            option name 'lan'
            list network 'lan'
            option input 'ACCEPT'
            option output 'ACCEPT'
            option forward 'ACCEPT'
        config zone
            option name 'wan'
            list network 'wan'
            option input 'REJECT'
            option output 'ACCEPT'
            option forward 'REJECT'
            option masq '1'
            option mtu_fix '1'
        config forwarding
            option src 'lan'
            option dest 'wan'
        config rule
            option name 'Allow-ssh'
            option src 'wan'
            option proto 'tcp'
            option dest_port '22'
            option family 'ipv4'
            option target 'ACCEPT'            
        config rule
            option name 'Allow-ping'
            option src 'wan'
            option proto 'icmp'
            option icmp_type 'echo-request'
            option family 'ipv4'
            option target 'ACCEPT'